apiVersion: v2
description: "Helm Chart for the Mojaloop (SDK-based) Simulator"
name: mojaloop-simulator
version: 14.2.1
appVersion: "sdk-scheme-adapter: v23.1.1; mojaloop-simulator: v14.0.2; thirdparty-sdk: v15.1.0"
dependencies:
  - name: common
    repository: "https://mojaloop.github.io/charts/repo"
    version: 2.0.0
    tags:
      - moja-common
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Tom Daly
    email: tomd@crosslaketech.com
  - name: Steven Oderayi
    email: steven.oderayi@infitx.com
