apiVersion: v2
description: ml-testing-toolkit-frontend Helm chart for Kubernetes
name: ml-testing-toolkit-frontend
version: 15.0.0
appVersion: "v15.0.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  -   https://github.com/mojaloop/mojaloop
  -   https://github.com/mojaloop/helm
  -   https://github.com/mojaloop/ml-testing-toolkit-ui
maintainers:
  -   name: Georgi Logodazhki
      email: georgi.logodazhki@modusbox.com
  -   name: Steven Oderayi
      email: steven.oderayi@modusbox.com
  -   name: Vijay Kumar Guthi
      email: vijaya.guthi@modusbox.com
  -   name: Tom Daly
      email: tomd@crosslaketech.com
dependencies:
  -   name: common
      repository: "https://docs.mojaloop.io/charts/repo"
      tags:
        -   moja-common
      version: 2.0.0
