{{- $forensicLoggingSidecarHost := printf "%s-%s" .Release.Name .Values.config.forensicloggingsidecar_host -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "centralledger-handler-transfer-prepare.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "centralledger-handler-transfer-prepare.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default.json") . ) | quote }}
  knexfile.js: {{ (tpl (.Files.Get "configs/knexfile.js") . ) | quote }}
  {{- if .Values.rules_settlement_model }}
  {{- if (typeIs "string" .Values.rules_settlement_model) }}
  rules_settlement_model.json: {{ .Values.rules_settlement_model | quote }}
  {{- else }}
  rules_settlement_model.json: {{ .Values.rules_settlement_model | toPrettyJson | quote }}
  {{- end }}
  {{- else }}
  rules_settlement_model.json: "[]"
  {{- end }}

{{- if .Values.sidecar.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "centralledger-handler-transfer-prepare.fullname" . }}-sidecar
  labels:
    app.kubernetes.io/name: {{ include "centralledger-handler-transfer-prepare.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default-sidecar.json") . ) | quote }}
{{- end }}
