{{- if .Values.scheduling.enabled }}
apiVersion: {{ template "ml-testing-toolkit-cli.apiVersion.CronJob" . }}
kind: CronJob
metadata:
  name: {{ template "ml-testing-toolkit-cli.fullname" . }}
spec:
  schedule: {{ .Values.scheduling.cronSchedule | quote }}
  suspend: {{ .Values.scheduling.suspend }}
  successfulJobsHistoryLimit: {{ .Values.scheduling.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.scheduling.failedJobsHistoryLimit }}
  timeZone: {{ .Values.scheduling.timeZone | quote }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- include "ml-testing-toolkit-cli.jobtemplate" . | nindent 6 }}
{{- end }}
{{- if .Values.job.enabled }} ## added job definition to values.yaml
apiVersion: {{ template "ml-testing-toolkit-cli.apiVersion.Job" . }}
kind: Job
metadata:
  name: {{ template "ml-testing-toolkit-cli.fullname" . }}
  annotations:
    {{- if .Values.postInstallHook.enabled }}
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": {{ .Values.postInstallHook.weight | quote }}
    "helm.sh/hook-delete-policy": {{ .Values.postInstallHook.deletePolicy }}
    {{- end }}
    ## Add custom annotations, and updated the values.yaml
spec:
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }} ## this would need to be added
  {{- end }}
  backoffLimit: {{ .Values.backoffLimit }}
  restartPolicy: {{ .Values.restartPolicy }}
  {{- include "ml-testing-toolkit-cli.jobtemplate" . | indent 2 }}
{{- end }}
