{{ if .Values.simulators }}
{{- $prefix := include "mojaloop-simulator.prefix" . -}}
apiVersion: {{ template "mojaloop-simulator.apiVersion.Ingress" . }}
kind: Ingress
metadata:
  name: {{ $prefix }}simulators
  labels:
    app.kubernetes.io/name: simulators
    {{- include "mojaloop-simulator.common-labels" $ | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
  rules:
  {{- range $name, $customConfig := .Values.simulators }}
  {{- $fullName := printf "%s%s" (include "mojaloop-simulator.prefix" $) $name -}}
  {{- $config := merge $customConfig $.Values.defaults }}
  {{- if $config.ingress.enabled -}}
    {{ $hosts := default (list nil) $config.ingress.hosts }}
    {{- range $host := $hosts }}
      - host: {{ $host }}
        http:
          paths:
          - path: /sim/{{ $name }}/outbound{{ $.Values.ingress.ingressPathRewriteRegex }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-scheme-adapter
                port:
                  number: {{ $config.config.schemeAdapter.env.OUTBOUND_LISTEN_PORT }}
          - path: /sim/{{ $name }}/inbound{{ $.Values.ingress.ingressPathRewriteRegex }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-scheme-adapter
                port:
                  number: {{ $config.config.schemeAdapter.env.INBOUND_LISTEN_PORT }}
          - path: /sim/{{ $name }}/sdktest{{ $.Values.ingress.ingressPathRewriteRegex }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-scheme-adapter
                port:
                  number: 3003
          - path: /sim/{{ $name }}/test{{ $.Values.ingress.ingressPathRewriteRegex }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-backend
                port:
                  number: 3003

    {{- end }}
  {{- end }}
  {{- end }}
---
{{ end }}
